// AUTO-GENERATED by scripts/build-fantasy-maps.mjs — do not edit by hand.
// Imaginary board "The Sundered Isles". Adjacency derived from shared Voronoi borders + sea-route links.
import {
  type GameMap, type Continent, type Territory, type TerritoryId, type ContinentId,
} from './map';

const CONTINENT_DEFS: ReadonlyArray<{
  id: ContinentId; name: string; bonus: number;
  territories: ReadonlyArray<readonly [TerritoryId, string]>;
}> = [
  {
    id: 'NA',
    name: "Coralhaven",
    bonus: 3,
    territories: [
      ['na-1', "Coralhaven"],
      ['na-2', "Saltspire"],
      ['na-3', "Tidewatch"],
      ['na-4', "Pearlreef"],
      ['na-5', "Stormcay"],
    ],
  },
  {
    id: 'EU',
    name: "Stormcay",
    bonus: 3,
    territories: [
      ['eu-1', "Driftmoor"],
      ['eu-2', "Brineport"],
      ['eu-3', "Gullrock"],
      ['eu-4', "Wavecrest"],
      ['eu-5', "Kelpholm"],
    ],
  },
  {
    id: 'AS',
    name: "Tidewatch",
    bonus: 3,
    territories: [
      ['as-1', "Foamreach"],
      ['as-2', "Mistral"],
      ['as-3', "Surfbreak"],
      ['as-4', "Lagoon"],
      ['as-5', "Marrowsand"],
    ],
  },
  {
    id: 'SA',
    name: "Driftmoor",
    bonus: 3,
    territories: [
      ['sa-1', "Seglas"],
      ['sa-2', "Anchorhold"],
      ['sa-3', "Reefgate"],
      ['sa-4', "Spindrift"],
      ['sa-5', "Halcyon"],
    ],
  },
  {
    id: 'AF',
    name: "Brineport",
    bonus: 3,
    territories: [
      ['af-1', "Bramblecay"],
      ['af-2', "Galewick"],
      ['af-3', "Netherstrand"],
      ['af-4', "Cinderkey"],
      ['af-5', "Whaleback"],
    ],
  },
  {
    id: 'AU',
    name: "Gullrock",
    bonus: 3,
    territories: [
      ['au-1', "Shoalhaven"],
      ['au-2', "Selkie"],
      ['au-3', "Tempest"],
      ['au-4', "Mariner"],
      ['au-5', "Azuredeep"],
    ],
  },
];

const EDGES: ReadonlyArray<readonly [TerritoryId, TerritoryId]> = [
  ['na-1', 'na-2'],
  ['na-1', 'na-5'],
  ['na-2', 'na-4'],
  ['na-2', 'na-5'],
  ['na-3', 'na-4'],
  ['na-3', 'na-5'],
  ['na-4', 'na-5'],
  ['eu-1', 'eu-3'],
  ['eu-1', 'eu-4'],
  ['eu-1', 'eu-5'],
  ['eu-2', 'eu-3'],
  ['eu-2', 'eu-4'],
  ['eu-3', 'eu-4'],
  ['eu-3', 'eu-5'],
  ['as-1', 'as-2'],
  ['as-1', 'as-3'],
  ['as-1', 'as-4'],
  ['as-1', 'as-5'],
  ['as-2', 'as-3'],
  ['as-2', 'as-4'],
  ['as-4', 'as-5'],
  ['sa-1', 'sa-3'],
  ['sa-1', 'sa-4'],
  ['sa-1', 'sa-5'],
  ['sa-2', 'sa-3'],
  ['sa-2', 'sa-5'],
  ['sa-3', 'sa-5'],
  ['sa-4', 'sa-5'],
  ['af-1', 'af-3'],
  ['af-1', 'af-4'],
  ['af-2', 'af-3'],
  ['af-2', 'af-4'],
  ['af-2', 'af-5'],
  ['af-3', 'af-4'],
  ['af-3', 'af-5'],
  ['au-1', 'au-2'],
  ['au-1', 'au-3'],
  ['au-2', 'au-3'],
  ['au-2', 'au-4'],
  ['au-2', 'au-5'],
  ['au-3', 'au-5'],
  ['au-4', 'au-5'],
  ['eu-2', 'na-1'],
  ['as-4', 'eu-5'],
  ['as-2', 'au-5'],
  ['af-4', 'au-4'],
  ['af-5', 'sa-1'],
  ['na-2', 'sa-4'],
  ['af-5', 'eu-2'],
  ['af-5', 'na-2'],
  ['af-4', 'as-2'],
];

const continents: Record<ContinentId, Continent> = {};
const territories: Record<TerritoryId, Territory> = {};
const allTerritoryIds: TerritoryId[] = [];
const adjacency: Record<TerritoryId, TerritoryId[]> = {};

for (const def of CONTINENT_DEFS) {
  const ids = def.territories.map(([id]) => id);
  continents[def.id] = { id: def.id, name: def.name, bonus: def.bonus, territories: ids };
  for (const [id, name] of def.territories) {
    territories[id] = { id, name, continent: def.id };
    allTerritoryIds.push(id);
    adjacency[id] = [];
  }
}
for (const [a, b] of EDGES) {
  if (!territories[a]) throw new Error(`isles map: edge references unknown territory '${a}'`);
  if (!territories[b]) throw new Error(`isles map: edge references unknown territory '${b}'`);
  if (!adjacency[a]!.includes(b)) adjacency[a]!.push(b);
  if (!adjacency[b]!.includes(a)) adjacency[b]!.push(a);
}

export const ISLES_MAP: GameMap = {
  id: 'isles',
  name: "The Sundered Isles",
  continents,
  territories,
  adjacency,
  allTerritoryIds,
};
