// AUTO-GENERATED by scripts/build-fantasy-maps.mjs — do not edit by hand.
// Imaginary board "The Long March". Adjacency derived from shared Voronoi borders + sea-route links.
import {
  type GameMap, type Continent, type Territory, type TerritoryId, type ContinentId,
} from './map';

const CONTINENT_DEFS: ReadonlyArray<{
  id: ContinentId; name: string; bonus: number;
  territories: ReadonlyArray<readonly [TerritoryId, string]>;
}> = [
  {
    id: 'NA',
    name: "Westwatch",
    bonus: 4,
    territories: [
      ['na-1', "Stonepass"],
      ['na-2', "Ironhold"],
      ['na-3', "Greycliff"],
      ['na-4', "Frostmarch"],
      ['na-5', "Granitega"],
      ['na-6', "Bleakmoor"],
    ],
  },
  {
    id: 'SA',
    name: "Greymarch",
    bonus: 4,
    territories: [
      ['sa-1', "Hammerfell"],
      ['sa-2', "Coldcrag"],
      ['sa-3', "Ridgewatch"],
      ['sa-4', "Flintvale"],
      ['sa-5', "Dourhall"],
      ['sa-6', "Slatereach"],
    ],
  },
  {
    id: 'EU',
    name: "Midhold",
    bonus: 5,
    territories: [
      ['eu-1', "Northpike"],
      ['eu-2', "Cragmaw"],
      ['eu-3', "Windgap"],
      ['eu-4', "Hollowstone"],
      ['eu-5', "Ashridge"],
      ['eu-6', "Boulderfen"],
      ['eu-7', "Snowmark"],
    ],
  },
  {
    id: 'AF',
    name: "Esthelm",
    bonus: 4,
    territories: [
      ['af-1', "Highreach"],
      ['af-2', "Dunmoor"],
      ['af-3', "Steelford"],
      ['af-4', "Rimecrest"],
      ['af-5', "Blackpass"],
      ['af-6', "Karngate"],
    ],
  },
  {
    id: 'AS',
    name: "Eastreach",
    bonus: 4,
    territories: [
      ['as-1', "Drystone"],
      ['as-2', "Talonridge"],
      ['as-3', "Greymarch"],
      ['as-4', "Frosthold"],
      ['as-5', "Stormgap"],
      ['as-6', "Wraithmoor"],
    ],
  },
];

const EDGES: ReadonlyArray<readonly [TerritoryId, TerritoryId]> = [
  ['na-1', 'na-2'],
  ['na-1', 'na-5'],
  ['na-1', 'na-6'],
  ['na-2', 'na-4'],
  ['na-2', 'na-5'],
  ['na-2', 'na-6'],
  ['na-3', 'na-4'],
  ['na-3', 'na-5'],
  ['na-4', 'na-5'],
  ['sa-1', 'sa-2'],
  ['sa-1', 'sa-5'],
  ['sa-1', 'sa-6'],
  ['sa-2', 'sa-4'],
  ['sa-2', 'sa-5'],
  ['sa-2', 'sa-6'],
  ['sa-3', 'sa-6'],
  ['sa-4', 'sa-5'],
  ['eu-1', 'eu-2'],
  ['eu-1', 'eu-3'],
  ['eu-1', 'eu-4'],
  ['eu-1', 'eu-6'],
  ['eu-1', 'eu-7'],
  ['eu-2', 'eu-3'],
  ['eu-2', 'eu-5'],
  ['eu-2', 'eu-6'],
  ['eu-3', 'eu-5'],
  ['eu-3', 'eu-7'],
  ['eu-4', 'eu-6'],
  ['af-1', 'af-2'],
  ['af-2', 'af-3'],
  ['af-2', 'af-5'],
  ['af-3', 'af-5'],
  ['af-3', 'af-6'],
  ['af-4', 'af-5'],
  ['af-4', 'af-6'],
  ['af-5', 'af-6'],
  ['as-1', 'as-4'],
  ['as-1', 'as-5'],
  ['as-2', 'as-3'],
  ['as-2', 'as-4'],
  ['as-2', 'as-6'],
  ['as-3', 'as-6'],
  ['as-4', 'as-5'],
  ['as-4', 'as-6'],
  ['na-4', 'sa-2'],
  ['eu-6', 'sa-5'],
  ['af-6', 'eu-7'],
  ['af-5', 'as-2'],
  ['af-3', 'sa-5'],
];

const continents: Record<ContinentId, Continent> = {};
const territories: Record<TerritoryId, Territory> = {};
const allTerritoryIds: TerritoryId[] = [];
const adjacency: Record<TerritoryId, TerritoryId[]> = {};

for (const def of CONTINENT_DEFS) {
  const ids = def.territories.map(([id]) => id);
  continents[def.id] = { id: def.id, name: def.name, bonus: def.bonus, territories: ids };
  for (const [id, name] of def.territories) {
    territories[id] = { id, name, continent: def.id };
    allTerritoryIds.push(id);
    adjacency[id] = [];
  }
}
for (const [a, b] of EDGES) {
  if (!territories[a]) throw new Error(`longmarch map: edge references unknown territory '${a}'`);
  if (!territories[b]) throw new Error(`longmarch map: edge references unknown territory '${b}'`);
  if (!adjacency[a]!.includes(b)) adjacency[a]!.push(b);
  if (!adjacency[b]!.includes(a)) adjacency[b]!.push(a);
}

export const LONGMARCH_MAP: GameMap = {
  id: 'longmarch',
  name: "The Long March",
  continents,
  territories,
  adjacency,
  allTerritoryIds,
};
