// AUTO-GENERATED by scripts/build-atlas-map.mjs — do not edit by hand.
// Board "The Storybook World". Positioned-seed atlas; adjacency from shared borders + sea routes.
import {
  type GameMap, type Continent, type Territory, type TerritoryId, type ContinentId,
} from './map';

const CONTINENT_DEFS: ReadonlyArray<{
  id: ContinentId; name: string; bonus: number;
  territories: ReadonlyArray<readonly [TerritoryId, string]>;
}> = [
  {
    id: 'emp',
    name: "Empyrea",
    bonus: 4,
    territories: [
      ['undying-lands', "Undying Lands"],
      ['asgard', "Asgard"],
      ['mount-olympus', "Mount Olympus"],
      ['shangri-la', "Shangri La"],
      ['el-dorado', "El Dorado"],
      ['turtle-island', "Turtle Island"],
    ],
  },
  {
    id: 'alb',
    name: "Albiona",
    bonus: 3,
    territories: [
      ['avalon', "Avalon"],
      ['camelot', "Camelot"],
      ['sherwood-forest', "Sherwood Forest"],
      ['cheshire-cat-wood', "Cheshire Cat Wood"],
      ['mad-hat', "Mad Hat"],
      ['queen-of-hearts', "Queen of Hearts Realm"],
    ],
  },
  {
    id: 'ard',
    name: "Ardania",
    bonus: 5,
    territories: [
      ['giant-land', "Giant Land"],
      ['lantern-waste', "Lantern Waste"],
      ['cair-paravel', "Cair Paravel"],
      ['the-shire', "The Shire"],
      ['rohan', "Rohan"],
      ['archenland', "Archenland"],
      ['mordor', "Mordor"],
      ['calormen', "Calormen"],
      ['gondor', "Gondor"],
    ],
  },
  {
    id: 'isl',
    name: "The Isles",
    bonus: 6,
    territories: [
      ['cyclops-land', "Cyclops Land"],
      ['loompa-land', "Loompa Land"],
      ['atlantis', "Atlantis"],
      ['utopia', "Utopia"],
      ['lilliput', "Lilliput"],
      ['jurassic-park', "Jurassic Park"],
      ['never-neverland', "Never Neverland"],
      ['wild-things', "Where the Wild Things Are"],
    ],
  },
  {
    id: 'mys',
    name: "Mystil",
    bonus: 3,
    territories: [
      ['lost-world', "The Lost World"],
      ['truffala-forest', "Truffala Tree Forest"],
      ['land-time-forgot', "The Land that Time Forgot"],
      ['fountain-of-youth', "Fountain of Youth"],
    ],
  },
  {
    id: 'ima',
    name: "Imagil",
    bonus: 4,
    territories: [
      ['hundred-acre-wood', "Hundred Acre Wood"],
      ['florin', "Florin"],
      ['guilder', "Guilder"],
      ['hogwarts', "Hogwarts"],
      ['forbidden-forest', "Forbidden Forest"],
      ['hogsmeade', "Hogsmeade"],
    ],
  },
  {
    id: 'wld',
    name: "The Wilds",
    bonus: 3,
    territories: [
      ['nool-jungle', "Nool Jungle"],
      ['elephant-land', "Elephant Land"],
      ['tarzan-jungle', "Tarzan Jungle"],
      ['rhino-land', "Rhino Land"],
      ['jumanji', "Jumanji"],
    ],
  },
  {
    id: 'ast',
    name: "Astoria",
    bonus: 6,
    territories: [
      ['castle-in-the-air', "Castle in the Air"],
      ['the-doldrums', "The Doldrums"],
      ['dictionopolis', "Dictionopolis"],
      ['digitopolis', "Digitopolis"],
      ['munchkin-land', "Munchkin Land"],
      ['emerald-city', "Emerald City"],
      ['sidewalk-ends', "Where the Sidewalk Ends"],
      ['wonka-factory', "Wonka Factory"],
      ['whoville', "Whoville"],
      ['fantasia', "Fantasia"],
    ],
  },
];

const EDGES: ReadonlyArray<readonly [TerritoryId, TerritoryId]> = [
  ['asgard', 'undying-lands'],
  ['asgard', 'mount-olympus'],
  ['mount-olympus', 'shangri-la'],
  ['el-dorado', 'shangri-la'],
  ['camelot', 'sherwood-forest'],
  ['camelot', 'cheshire-cat-wood'],
  ['cheshire-cat-wood', 'sherwood-forest'],
  ['mad-hat', 'sherwood-forest'],
  ['cheshire-cat-wood', 'mad-hat'],
  ['cheshire-cat-wood', 'queen-of-hearts'],
  ['mad-hat', 'queen-of-hearts'],
  ['giant-land', 'lantern-waste'],
  ['giant-land', 'the-shire'],
  ['giant-land', 'rohan'],
  ['cair-paravel', 'lantern-waste'],
  ['lantern-waste', 'rohan'],
  ['cair-paravel', 'rohan'],
  ['archenland', 'cair-paravel'],
  ['rohan', 'the-shire'],
  ['gondor', 'the-shire'],
  ['archenland', 'rohan'],
  ['mordor', 'rohan'],
  ['gondor', 'rohan'],
  ['archenland', 'mordor'],
  ['archenland', 'calormen'],
  ['calormen', 'mordor'],
  ['gondor', 'mordor'],
  ['calormen', 'gondor'],
  ['lost-world', 'truffala-forest'],
  ['land-time-forgot', 'lost-world'],
  ['land-time-forgot', 'truffala-forest'],
  ['fountain-of-youth', 'land-time-forgot'],
  ['florin', 'hundred-acre-wood'],
  ['guilder', 'hundred-acre-wood'],
  ['florin', 'guilder'],
  ['florin', 'hogwarts'],
  ['guilder', 'hogwarts'],
  ['hogsmeade', 'hogwarts'],
  ['elephant-land', 'nool-jungle'],
  ['nool-jungle', 'tarzan-jungle'],
  ['elephant-land', 'tarzan-jungle'],
  ['elephant-land', 'rhino-land'],
  ['rhino-land', 'tarzan-jungle'],
  ['jumanji', 'tarzan-jungle'],
  ['jumanji', 'rhino-land'],
  ['castle-in-the-air', 'the-doldrums'],
  ['castle-in-the-air', 'dictionopolis'],
  ['castle-in-the-air', 'emerald-city'],
  ['dictionopolis', 'the-doldrums'],
  ['digitopolis', 'the-doldrums'],
  ['munchkin-land', 'the-doldrums'],
  ['emerald-city', 'the-doldrums'],
  ['dictionopolis', 'digitopolis'],
  ['digitopolis', 'munchkin-land'],
  ['emerald-city', 'munchkin-land'],
  ['emerald-city', 'whoville'],
  ['whoville', 'wonka-factory'],
  ['el-dorado', 'turtle-island'],
  ['avalon', 'undying-lands'],
  ['asgard', 'avalon'],
  ['cyclops-land', 'mount-olympus'],
  ['el-dorado', 'hundred-acre-wood'],
  ['atlantis', 'shangri-la'],
  ['cheshire-cat-wood', 'cyclops-land'],
  ['giant-land', 'queen-of-hearts'],
  ['avalon', 'camelot'],
  ['archenland', 'lilliput'],
  ['calormen', 'sidewalk-ends'],
  ['fantasia', 'gondor'],
  ['cair-paravel', 'utopia'],
  ['cyclops-land', 'loompa-land'],
  ['atlantis', 'cyclops-land'],
  ['loompa-land', 'utopia'],
  ['atlantis', 'utopia'],
  ['atlantis', 'jurassic-park'],
  ['lilliput', 'utopia'],
  ['jurassic-park', 'never-neverland'],
  ['never-neverland', 'utopia'],
  ['never-neverland', 'wild-things'],
  ['atlantis', 'land-time-forgot'],
  ['jurassic-park', 'lost-world'],
  ['fountain-of-youth', 'jurassic-park'],
  ['lilliput', 'sidewalk-ends'],
  ['castle-in-the-air', 'utopia'],
  ['dictionopolis', 'never-neverland'],
  ['forbidden-forest', 'wild-things'],
  ['nool-jungle', 'wild-things'],
  ['hundred-acre-wood', 'lost-world'],
  ['fountain-of-youth', 'guilder'],
  ['forbidden-forest', 'nool-jungle'],
  ['hogsmeade', 'nool-jungle'],
  ['digitopolis', 'jumanji'],
];

const continents: Record<ContinentId, Continent> = {};
const territories: Record<TerritoryId, Territory> = {};
const allTerritoryIds: TerritoryId[] = [];
const adjacency: Record<TerritoryId, TerritoryId[]> = {};

for (const def of CONTINENT_DEFS) {
  const cids = def.territories.map(([id]) => id);
  continents[def.id] = { id: def.id, name: def.name, bonus: def.bonus, territories: cids };
  for (const [id, name] of def.territories) {
    territories[id] = { id, name, continent: def.id };
    allTerritoryIds.push(id);
    adjacency[id] = [];
  }
}
for (const [a, b] of EDGES) {
  if (!territories[a]) throw new Error(`storybook map: edge references unknown territory '${a}'`);
  if (!territories[b]) throw new Error(`storybook map: edge references unknown territory '${b}'`);
  if (!adjacency[a]!.includes(b)) adjacency[a]!.push(b);
  if (!adjacency[b]!.includes(a)) adjacency[b]!.push(a);
}

export const STORYBOOK_MAP: GameMap = {
  id: 'storybook',
  name: "The Storybook World",
  continents,
  territories,
  adjacency,
  allTerritoryIds,
};
