// AUTO-GENERATED by scripts/build-fantasy-maps.mjs — do not edit by hand.
// Imaginary board "Twin Crowns". Adjacency derived from shared Voronoi borders + sea-route links.
import {
  type GameMap, type Continent, type Territory, type TerritoryId, type ContinentId,
} from './map';

const CONTINENT_DEFS: ReadonlyArray<{
  id: ContinentId; name: string; bonus: number;
  territories: ReadonlyArray<readonly [TerritoryId, string]>;
}> = [
  {
    id: 'NA',
    name: "The West Crown",
    bonus: 6,
    territories: [
      ['na-1', "Goldthrone"],
      ['na-2', "Crownreach"],
      ['na-3', "Regalia"],
      ['na-4', "Scepterhold"],
      ['na-5', "Velvetmoor"],
      ['na-6', "Diadem"],
      ['na-7', "Kingsmere"],
      ['na-8', "Argentvale"],
      ['na-9', "Ermine"],
      ['na-10', "Sovereign"],
      ['na-11', "Coronet"],
    ],
  },
  {
    id: 'AS',
    name: "The East Crown",
    bonus: 6,
    territories: [
      ['as-1', "Throneward"],
      ['as-2', "Gildspire"],
      ['as-3', "Ruby March"],
      ['as-4', "Opaline"],
      ['as-5', "Majesthold"],
      ['as-6', "Castellan"],
      ['as-7', "Bastion"],
      ['as-8', "Highcrown"],
      ['as-9', "Emberthrone"],
      ['as-10', "Silvercrown"],
      ['as-11', "Dawnscepter"],
    ],
  },
  {
    id: 'EU',
    name: "Northgate",
    bonus: 2,
    territories: [
      ['eu-1', "Garnet"],
      ['eu-2', "Imperia"],
      ['eu-3', "Lordsreach"],
    ],
  },
  {
    id: 'AF',
    name: "Southgate",
    bonus: 2,
    territories: [
      ['af-1', "Mantlewood"],
      ['af-2', "Court"],
      ['af-3', "Heralds"],
    ],
  },
];

const EDGES: ReadonlyArray<readonly [TerritoryId, TerritoryId]> = [
  ['na-1', 'na-2'],
  ['na-1', 'na-3'],
  ['na-1', 'na-9'],
  ['na-1', 'na-10'],
  ['na-2', 'na-9'],
  ['na-3', 'na-6'],
  ['na-10', 'na-3'],
  ['na-4', 'na-5'],
  ['na-4', 'na-6'],
  ['na-4', 'na-7'],
  ['na-4', 'na-8'],
  ['na-4', 'na-9'],
  ['na-10', 'na-4'],
  ['na-11', 'na-4'],
  ['na-5', 'na-7'],
  ['na-5', 'na-9'],
  ['na-6', 'na-8'],
  ['na-10', 'na-6'],
  ['na-11', 'na-7'],
  ['na-11', 'na-8'],
  ['na-10', 'na-9'],
  ['as-1', 'as-5'],
  ['as-1', 'as-6'],
  ['as-1', 'as-8'],
  ['as-1', 'as-9'],
  ['as-1', 'as-10'],
  ['as-2', 'as-3'],
  ['as-2', 'as-5'],
  ['as-2', 'as-9'],
  ['as-11', 'as-2'],
  ['as-3', 'as-4'],
  ['as-3', 'as-7'],
  ['as-3', 'as-9'],
  ['as-4', 'as-7'],
  ['as-5', 'as-8'],
  ['as-5', 'as-9'],
  ['as-11', 'as-5'],
  ['as-6', 'as-7'],
  ['as-6', 'as-9'],
  ['as-10', 'as-6'],
  ['as-7', 'as-9'],
  ['as-11', 'as-8'],
  ['eu-1', 'eu-2'],
  ['eu-1', 'eu-3'],
  ['eu-2', 'eu-3'],
  ['af-1', 'af-2'],
  ['af-1', 'af-3'],
  ['af-2', 'af-3'],
  ['eu-1', 'na-7'],
  ['as-3', 'eu-2'],
  ['af-1', 'na-7'],
  ['af-3', 'as-3'],
  ['af-3', 'eu-1'],
];

const continents: Record<ContinentId, Continent> = {};
const territories: Record<TerritoryId, Territory> = {};
const allTerritoryIds: TerritoryId[] = [];
const adjacency: Record<TerritoryId, TerritoryId[]> = {};

for (const def of CONTINENT_DEFS) {
  const ids = def.territories.map(([id]) => id);
  continents[def.id] = { id: def.id, name: def.name, bonus: def.bonus, territories: ids };
  for (const [id, name] of def.territories) {
    territories[id] = { id, name, continent: def.id };
    allTerritoryIds.push(id);
    adjacency[id] = [];
  }
}
for (const [a, b] of EDGES) {
  if (!territories[a]) throw new Error(`twincrowns map: edge references unknown territory '${a}'`);
  if (!territories[b]) throw new Error(`twincrowns map: edge references unknown territory '${b}'`);
  if (!adjacency[a]!.includes(b)) adjacency[a]!.push(b);
  if (!adjacency[b]!.includes(a)) adjacency[b]!.push(a);
}

export const TWINCROWNS_MAP: GameMap = {
  id: 'twincrowns',
  name: "Twin Crowns",
  continents,
  territories,
  adjacency,
  allTerritoryIds,
};
