// AUTO-GENERATED by scripts/build-atlas-map.mjs — do not edit by hand.
// Board "United Kingdom". Positioned-seed atlas; adjacency from shared borders + sea routes.
import {
  type GameMap, type Continent, type Territory, type TerritoryId, type ContinentId,
} from './map';

const CONTINENT_DEFS: ReadonlyArray<{
  id: ContinentId; name: string; bonus: number;
  territories: ReadonlyArray<readonly [TerritoryId, string]>;
}> = [
  {
    id: 'uk-eng',
    name: "England",
    bonus: 7,
    territories: [
      ['north-england', "North England"],
      ['yorkshire-humber', "Yorkshire & the Humber"],
      ['north-west-england', "North West England"],
      ['west-midlands', "West Midlands"],
      ['east-midlands', "East Midlands"],
      ['east-anglia', "East Anglia"],
      ['heart-of-england', "Heart of England"],
      ['gloucestershire', "Gloucestershire"],
      ['london', "London"],
      ['southern-england', "Southern England"],
      ['south-west-england', "South West England"],
    ],
  },
  {
    id: 'uk-ire',
    name: "Ireland",
    bonus: 6,
    territories: [
      ['donegal', "Donegal"],
      ['monaghan', "Monaghan"],
      ['meath', "Meath"],
      ['dublin', "Dublin"],
      ['galway', "Galway"],
      ['kilkenny', "Kilkenny"],
      ['tipperary', "Tipperary"],
      ['clare', "Clare"],
      ['cork', "Cork"],
      ['kerry', "Kerry"],
    ],
  },
  {
    id: 'uk-nire',
    name: "Northern Ireland",
    bonus: 4,
    territories: [
      ['londonderry', "Londonderry"],
      ['antrim', "Antrim"],
      ['tyrone', "Tyrone"],
      ['armagh', "Armagh"],
      ['down', "Down"],
    ],
  },
  {
    id: 'uk-ssco',
    name: "Southern Scotland",
    bonus: 4,
    territories: [
      ['argyll', "Argyll"],
      ['tayside', "Tayside"],
      ['glasgow-edinburgh', "Glasgow & Edinburgh"],
      ['the-borders', "The Borders"],
      ['dumfries-galloway', "Dumfries & Galloway"],
    ],
  },
  {
    id: 'uk-wal',
    name: "Wales",
    bonus: 3,
    territories: [
      ['anglesey', "Anglesey"],
      ['snowdonia', "Snowdonia"],
      ['mid-wales', "Mid Wales"],
      ['ceredigion', "Ceredigion"],
      ['pembrokeshire', "Pembrokeshire"],
      ['cardiff', "Cardiff"],
    ],
  },
  {
    id: 'uk-nsco',
    name: "Northern Scotland",
    bonus: 2,
    territories: [
      ['highland', "Highland"],
      ['grampian', "Grampian"],
      ['western-isles', "Western Isles"],
      ['orkney-isles', "Orkney Isles"],
      ['shetland-isles', "Shetland Isles"],
    ],
  },
];

const EDGES: ReadonlyArray<readonly [TerritoryId, TerritoryId]> = [
  ['grampian', 'highland'],
  ['argyll', 'highland'],
  ['argyll', 'grampian'],
  ['grampian', 'tayside'],
  ['argyll', 'tayside'],
  ['argyll', 'glasgow-edinburgh'],
  ['glasgow-edinburgh', 'tayside'],
  ['tayside', 'the-borders'],
  ['glasgow-edinburgh', 'the-borders'],
  ['dumfries-galloway', 'glasgow-edinburgh'],
  ['dumfries-galloway', 'the-borders'],
  ['north-england', 'the-borders'],
  ['the-borders', 'yorkshire-humber'],
  ['dumfries-galloway', 'north-england'],
  ['antrim', 'londonderry'],
  ['londonderry', 'tyrone'],
  ['armagh', 'londonderry'],
  ['donegal', 'londonderry'],
  ['antrim', 'armagh'],
  ['antrim', 'down'],
  ['armagh', 'tyrone'],
  ['donegal', 'tyrone'],
  ['monaghan', 'tyrone'],
  ['galway', 'tyrone'],
  ['armagh', 'down'],
  ['armagh', 'monaghan'],
  ['armagh', 'meath'],
  ['down', 'meath'],
  ['down', 'dublin'],
  ['donegal', 'galway'],
  ['meath', 'monaghan'],
  ['galway', 'monaghan'],
  ['dublin', 'meath'],
  ['galway', 'meath'],
  ['kilkenny', 'meath'],
  ['dublin', 'kilkenny'],
  ['galway', 'kilkenny'],
  ['clare', 'galway'],
  ['kilkenny', 'tipperary'],
  ['clare', 'kilkenny'],
  ['clare', 'tipperary'],
  ['cork', 'tipperary'],
  ['clare', 'cork'],
  ['anglesey', 'snowdonia'],
  ['anglesey', 'north-england'],
  ['anglesey', 'north-west-england'],
  ['anglesey', 'west-midlands'],
  ['mid-wales', 'snowdonia'],
  ['ceredigion', 'snowdonia'],
  ['snowdonia', 'west-midlands'],
  ['ceredigion', 'mid-wales'],
  ['cardiff', 'mid-wales'],
  ['mid-wales', 'west-midlands'],
  ['heart-of-england', 'mid-wales'],
  ['gloucestershire', 'mid-wales'],
  ['ceredigion', 'pembrokeshire'],
  ['cardiff', 'ceredigion'],
  ['cardiff', 'pembrokeshire'],
  ['pembrokeshire', 'south-west-england'],
  ['cardiff', 'gloucestershire'],
  ['cardiff', 'southern-england'],
  ['cardiff', 'south-west-england'],
  ['north-england', 'yorkshire-humber'],
  ['north-england', 'north-west-england'],
  ['north-west-england', 'yorkshire-humber'],
  ['east-midlands', 'yorkshire-humber'],
  ['north-west-england', 'west-midlands'],
  ['east-midlands', 'north-west-england'],
  ['east-midlands', 'west-midlands'],
  ['heart-of-england', 'west-midlands'],
  ['east-anglia', 'east-midlands'],
  ['east-midlands', 'heart-of-england'],
  ['east-anglia', 'heart-of-england'],
  ['east-anglia', 'london'],
  ['gloucestershire', 'heart-of-england'],
  ['heart-of-england', 'london'],
  ['gloucestershire', 'london'],
  ['gloucestershire', 'southern-england'],
  ['london', 'southern-england'],
  ['south-west-england', 'southern-england'],
  ['highland', 'western-isles'],
  ['highland', 'orkney-isles'],
  ['grampian', 'orkney-isles'],
  ['orkney-isles', 'shetland-isles'],
  ['down', 'dumfries-galloway'],
  ['down', 'north-west-england'],
  ['dublin', 'north-west-england'],
  ['anglesey', 'dublin'],
  ['cork', 'south-west-england'],
  ['cork', 'kerry'],
];

const continents: Record<ContinentId, Continent> = {};
const territories: Record<TerritoryId, Territory> = {};
const allTerritoryIds: TerritoryId[] = [];
const adjacency: Record<TerritoryId, TerritoryId[]> = {};

for (const def of CONTINENT_DEFS) {
  const cids = def.territories.map(([id]) => id);
  continents[def.id] = { id: def.id, name: def.name, bonus: def.bonus, territories: cids };
  for (const [id, name] of def.territories) {
    territories[id] = { id, name, continent: def.id };
    allTerritoryIds.push(id);
    adjacency[id] = [];
  }
}
for (const [a, b] of EDGES) {
  if (!territories[a]) throw new Error(`uk map: edge references unknown territory '${a}'`);
  if (!territories[b]) throw new Error(`uk map: edge references unknown territory '${b}'`);
  if (!adjacency[a]!.includes(b)) adjacency[a]!.push(b);
  if (!adjacency[b]!.includes(a)) adjacency[b]!.push(a);
}

export const UK_MAP: GameMap = {
  id: 'uk',
  name: "United Kingdom",
  continents,
  territories,
  adjacency,
  allTerritoryIds,
};
