// AUTO-GENERATED by scripts/build-fantasy-maps.mjs — do not edit by hand.
// Imaginary board "Verdantia". Adjacency derived from shared Voronoi borders + sea-route links.
import {
  type GameMap, type Continent, type Territory, type TerritoryId, type ContinentId,
} from './map';

const CONTINENT_DEFS: ReadonlyArray<{
  id: ContinentId; name: string; bonus: number;
  territories: ReadonlyArray<readonly [TerritoryId, string]>;
}> = [
  {
    id: 'AS',
    name: "The Heartland",
    bonus: 5,
    territories: [
      ['as-1', "Thornwild"],
      ['as-2', "Oakhollow"],
      ['as-3', "Mossvale"],
      ['as-4', "Fernreach"],
      ['as-5', "Briarfen"],
      ['as-6', "Elderwood"],
      ['as-7', "Greenmarch"],
      ['as-8', "Willowdeep"],
    ],
  },
  {
    id: 'NA',
    name: "Norvale",
    bonus: 4,
    territories: [
      ['na-1', "Sunmeadow"],
      ['na-2', "Cedargrove"],
      ['na-3', "Hawthorn"],
      ['na-4', "Bramblewood"],
      ['na-5', "Larkspur"],
      ['na-6', "Hollowmere"],
      ['na-7', "Duskfen"],
      ['na-8', "Ivybrook"],
    ],
  },
  {
    id: 'EU',
    name: "Estmark",
    bonus: 4,
    territories: [
      ['eu-1', "Wolfsden"],
      ['eu-2', "Stagmoor"],
      ['eu-3', "Honeyvale"],
      ['eu-4', "Reedmarsh"],
      ['eu-5', "Foxglade"],
      ['eu-6', "Ashbourne"],
      ['eu-7', "Birchholt"],
    ],
  },
  {
    id: 'SA',
    name: "Sudreach",
    bonus: 4,
    territories: [
      ['sa-1', "Nettlewood"],
      ['sa-2', "Quillvale"],
      ['sa-3', "Rowanhill"],
      ['sa-4', "Marshlight"],
      ['sa-5', "Pinecrest"],
      ['sa-6', "Gladewater"],
      ['sa-7', "Emberfern"],
    ],
  },
  {
    id: 'AF',
    name: "Austfen",
    bonus: 5,
    territories: [
      ['af-1', "Thistledown"],
      ['af-2', "Wyrmwood"],
      ['af-3', "Silverbark"],
      ['af-4', "Dewfall"],
      ['af-5', "Cloverlea"],
      ['af-6', "Bracken"],
      ['af-7', "Mistwood"],
      ['af-8', "Vinereach"],
    ],
  },
];

const EDGES: ReadonlyArray<readonly [TerritoryId, TerritoryId]> = [
  ['as-1', 'as-2'],
  ['as-1', 'as-7'],
  ['as-2', 'as-3'],
  ['as-2', 'as-5'],
  ['as-2', 'as-7'],
  ['as-3', 'as-4'],
  ['as-3', 'as-5'],
  ['as-3', 'as-6'],
  ['as-3', 'as-7'],
  ['as-4', 'as-5'],
  ['as-4', 'as-6'],
  ['as-4', 'as-8'],
  ['as-6', 'as-7'],
  ['as-6', 'as-8'],
  ['na-1', 'na-5'],
  ['na-1', 'na-6'],
  ['na-2', 'na-3'],
  ['na-2', 'na-4'],
  ['na-2', 'na-6'],
  ['na-2', 'na-7'],
  ['na-3', 'na-4'],
  ['na-3', 'na-5'],
  ['na-3', 'na-6'],
  ['na-4', 'na-7'],
  ['na-4', 'na-8'],
  ['na-5', 'na-6'],
  ['na-7', 'na-8'],
  ['eu-1', 'eu-2'],
  ['eu-1', 'eu-3'],
  ['eu-1', 'eu-7'],
  ['eu-2', 'eu-3'],
  ['eu-2', 'eu-4'],
  ['eu-2', 'eu-6'],
  ['eu-2', 'eu-7'],
  ['eu-3', 'eu-5'],
  ['eu-3', 'eu-6'],
  ['eu-4', 'eu-6'],
  ['eu-4', 'eu-7'],
  ['eu-5', 'eu-6'],
  ['sa-1', 'sa-3'],
  ['sa-1', 'sa-5'],
  ['sa-1', 'sa-6'],
  ['sa-2', 'sa-4'],
  ['sa-2', 'sa-5'],
  ['sa-2', 'sa-6'],
  ['sa-3', 'sa-4'],
  ['sa-3', 'sa-5'],
  ['sa-3', 'sa-7'],
  ['sa-4', 'sa-5'],
  ['sa-4', 'sa-7'],
  ['sa-5', 'sa-6'],
  ['af-1', 'af-3'],
  ['af-1', 'af-5'],
  ['af-1', 'af-8'],
  ['af-2', 'af-3'],
  ['af-2', 'af-4'],
  ['af-2', 'af-6'],
  ['af-2', 'af-7'],
  ['af-2', 'af-8'],
  ['af-3', 'af-8'],
  ['af-4', 'af-6'],
  ['af-4', 'af-8'],
  ['af-5', 'af-8'],
  ['af-6', 'af-7'],
  ['as-1', 'na-8'],
  ['as-8', 'eu-4'],
  ['as-5', 'sa-1'],
  ['af-1', 'as-8'],
  ['eu-5', 'na-7'],
  ['af-5', 'sa-1'],
  ['na-8', 'sa-1'],
  ['af-1', 'eu-4'],
];

const continents: Record<ContinentId, Continent> = {};
const territories: Record<TerritoryId, Territory> = {};
const allTerritoryIds: TerritoryId[] = [];
const adjacency: Record<TerritoryId, TerritoryId[]> = {};

for (const def of CONTINENT_DEFS) {
  const ids = def.territories.map(([id]) => id);
  continents[def.id] = { id: def.id, name: def.name, bonus: def.bonus, territories: ids };
  for (const [id, name] of def.territories) {
    territories[id] = { id, name, continent: def.id };
    allTerritoryIds.push(id);
    adjacency[id] = [];
  }
}
for (const [a, b] of EDGES) {
  if (!territories[a]) throw new Error(`verdantia map: edge references unknown territory '${a}'`);
  if (!territories[b]) throw new Error(`verdantia map: edge references unknown territory '${b}'`);
  if (!adjacency[a]!.includes(b)) adjacency[a]!.push(b);
  if (!adjacency[b]!.includes(a)) adjacency[b]!.push(a);
}

export const VERDANTIA_MAP: GameMap = {
  id: 'verdantia',
  name: "Verdantia",
  continents,
  territories,
  adjacency,
  allTerritoryIds,
};
